apiVersion: v1
kind: ConfigMap
metadata:
  name: fern-config
  labels:
    {{- include "fern.labels" . | nindent 4 }}
data:
  FERN_USE_DB: {{ .Values.backend.env.FERN_USE_DB | quote }}
  CORS_ORIGINS: {{ .Values.backend.env.CORS_ORIGINS | quote }}
  FERN_API_BASE_URL: {{ .Values.mcp.env.FERN_API_BASE_URL | quote }}
