{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.database.existingSecret }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fern.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRefName }}
    kind: {{ .Values.externalSecret.secretStoreRefKind }}
  target:
    name: {{ .Values.database.existingSecret }}
  data:
    - secretKey: {{ .Values.database.databaseUrlKey }}
      remoteRef:
        key: {{ .Values.externalSecret.remoteDatabaseUrlKey }}
{{- end }}
