{{- $root := . -}}
{{- if $root.Values.infraSettings -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "fern.infraSecretName" $root }}
  namespace: {{ $root.Values.namespace }}
  labels:
    {{- include "fern.labels" $root | nindent 4 }}
data:
  {{- range $settingKey, $settingValue := $root.Values.requiredInfraDependencies.values }}
  {{- if hasPrefix "$" $settingValue }}
  {{- $settingValueKey := trimPrefix "$" $settingValue }}
  {{- $actualSettingValue := pluck $settingValueKey $root.Values.infraSettings | first }}
  {{- if and $actualSettingValue (ne $actualSettingValue "") }}
  {{ $settingKey }}: {{ $actualSettingValue | quote }}
  {{- end }}
  {{- else if and $settingValue (ne $settingValue "") }}
  {{ $settingKey }}: {{ $settingValue | quote }}
  {{- end }}
  {{- end }}
---
{{- end }}
