apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccountName }}
  labels:
    {{- include "fern.labels" . | nindent 4 }}
  {{- if .Values.backend.irsaRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.backend.irsaRoleArn | quote }}
  {{- end }}
