apiVersion: v1
kind: Service
metadata:
  name: fern-backend
  labels:
    {{- include "fern.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: fern
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: http
