import { BarChart3, Hash, Loader2, FileQuestion } from 'lucide-react';
import { useStatisticsFiles, useTableStatistics } from '../../hooks/useIcebergData';
import type { ColumnStatistics } from '../../types/iceberg';

interface PuffinViewerProps {
  catalog: string;
  namespace: string;
  table: string;
  snapshotId?: number;
}

interface StatCardProps {
  stat: ColumnStatistics;
}

function StatCard({ stat }: StatCardProps) {
  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-4">
      <div className="flex items-start justify-between mb-3">
        <div>
          <h4 className="font-medium text-gray-900 dark:text-white">
            {stat.column_name || `Column ${stat.column_id}`}
          </h4>
          <p className="text-xs text-gray-500">ID: {stat.column_id}</p>
        </div>
        <div className="p-2 bg-purple-100 dark:bg-purple-900/30 rounded-lg">
          <Hash className="w-4 h-4 text-purple-600 dark:text-purple-400" />
        </div>
      </div>

      {stat.ndv !== null && stat.ndv !== undefined && (
        <div className="mb-3">
          <p className="text-xs text-gray-500 mb-1">Distinct Values (NDV)</p>
          <p className="text-2xl font-bold text-gray-900 dark:text-white">
            {stat.ndv.toLocaleString()}
          </p>
          {stat.ndv_estimate_lower !== undefined && stat.ndv_estimate_upper !== undefined && (
            <p className="text-xs text-gray-400">
              Range: {stat.ndv_estimate_lower.toLocaleString()} - {stat.ndv_estimate_upper.toLocaleString()}
            </p>
          )}
        </div>
      )}

      {stat.null_count !== null && stat.null_count !== undefined && (
        <div className="mb-3">
          <p className="text-xs text-gray-500 mb-1">Null Count</p>
          <p className="text-lg font-semibold text-gray-700 dark:text-gray-300">
            {stat.null_count.toLocaleString()}
          </p>
        </div>
      )}

      {(stat.min_value !== null || stat.max_value !== null) && (
        <div className="grid grid-cols-2 gap-2">
          {stat.min_value !== null && (
            <div>
              <p className="text-xs text-gray-500">Min</p>
              <p className="text-sm font-mono text-gray-700 dark:text-gray-300 truncate">
                {String(stat.min_value)}
              </p>
            </div>
          )}
          {stat.max_value !== null && (
            <div>
              <p className="text-xs text-gray-500">Max</p>
              <p className="text-sm font-mono text-gray-700 dark:text-gray-300 truncate">
                {String(stat.max_value)}
              </p>
            </div>
          )}
        </div>
      )}

      {stat.blob_type && (
        <div className="mt-3 pt-3 border-t border-gray-100 dark:border-gray-700">
          <p className="text-xs text-gray-400">
            Source: {stat.blob_type}
          </p>
        </div>
      )}
    </div>
  );
}

export function PuffinViewer({
  catalog,
  namespace,
  table,
  snapshotId,
}: PuffinViewerProps) {
  const { data: puffinFiles, isLoading: loadingFiles } = useStatisticsFiles(
    catalog,
    namespace,
    table
  );

  const { data: statistics, isLoading: loadingStats } = useTableStatistics(
    catalog,
    namespace,
    table,
    snapshotId || 0
  );

  const isLoading = loadingFiles || loadingStats;

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-8">
        <Loader2 className="w-6 h-6 animate-spin text-gray-400" />
      </div>
    );
  }

  if (!puffinFiles || puffinFiles.length === 0) {
    return (
      <div className="p-4">
        <div className="text-center py-8">
          <FileQuestion className="w-12 h-12 mx-auto text-gray-300 dark:text-gray-600 mb-4" />
          <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-2">
            No Statistics Available
          </h3>
          <p className="text-sm text-gray-500">
            This table doesn't have any Puffin statistics files.
          </p>
          <p className="text-xs text-gray-400 mt-2">
            Statistics are generated by running ANALYZE TABLE or similar operations.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="p-4 space-y-4">
      <div>
        <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
          Table Statistics
        </h3>
        <p className="text-sm text-gray-500">
          {puffinFiles.length} statistics file(s) available
        </p>
      </div>

      {/* Puffin files summary */}
      <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-4">
        <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">
          Statistics Files
        </h4>
        <div className="space-y-2">
          {puffinFiles.map((file, idx) => (
            <div
              key={idx}
              className="flex items-center justify-between text-sm"
            >
              <div className="flex items-center gap-2">
                <BarChart3 className="w-4 h-4 text-purple-500" />
                <span className="font-mono text-xs truncate max-w-[200px]">
                  {file.file_path.split('/').pop()}
                </span>
              </div>
              <div className="flex items-center gap-4 text-gray-500">
                <span>Snapshot: {file.snapshot_id}</span>
                <span>{file.blob_count} blobs</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Column statistics */}
      {statistics && statistics.column_statistics.length > 0 && (
        <div>
          <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">
            Column Statistics (Snapshot #{snapshotId?.toString().slice(-6)})
          </h4>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {statistics.column_statistics.map((stat, idx) => (
              <StatCard key={idx} stat={stat} />
            ))}
          </div>
        </div>
      )}

      {statistics && statistics.column_statistics.length === 0 && (
        <div className="text-center py-4 text-gray-500">
          <p>No column statistics decoded for this snapshot.</p>
        </div>
      )}
    </div>
  );
}
